services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Moscow
    network_mode: host
    depends_on:
      - matter-server
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    privileged: true

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./matter:/data
    environment:
      - TZ=Europe/Moscow
